name: cooking_book
description: CookBook Pro - Flutter application with BLoC state management

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  envied: ^1.3.2  # актуальна версія envied

  # Firebase
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.1.6
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.4.5
  google_sign_in: ^6.2.2

  # State Management - BLoC
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # UI
  cupertino_icons: ^1.0.8

  # Image picker
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  envied_generator: ^1.3.2  # актуальна версія генератора

#aboba
flutter:
  uses-material-design: true
